# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Programs\Github\My_Repos\PyQt_Socius\designer_files\snippets_tab_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SnippetsTab(object):
    def setupUi(self, SnippetsTab):
        SnippetsTab.setObjectName("SnippetsTab")
        SnippetsTab.resize(1363, 1102)
        self.gridLayout = QtWidgets.QGridLayout(SnippetsTab)
        self.gridLayout.setObjectName("gridLayout")
        self.change_font_pushButton = QtWidgets.QPushButton(SnippetsTab)
        self.change_font_pushButton.setObjectName("change_font_pushButton")
        self.gridLayout.addWidget(self.change_font_pushButton, 2, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(SnippetsTab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.snippets_tableView = SnippetsTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snippets_tableView.sizePolicy().hasHeightForWidth())
        self.snippets_tableView.setSizePolicy(sizePolicy)
        self.snippets_tableView.setMinimumSize(QtCore.QSize(0, 350))
        self.snippets_tableView.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.snippets_tableView.setObjectName("snippets_tableView")
        self.snippet_preview_Scintilla = Qsci.QsciScintilla(self.splitter)
        self.snippet_preview_Scintilla.setStyleSheet("")
        self.snippet_preview_Scintilla.setObjectName("snippet_preview_Scintilla")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(1162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.new_snippet_pushButton = QtWidgets.QPushButton(SnippetsTab)
        self.new_snippet_pushButton.setObjectName("new_snippet_pushButton")
        self.gridLayout.addWidget(self.new_snippet_pushButton, 0, 2, 1, 1)
        self.delete_snippet_pushButton = QtWidgets.QPushButton(SnippetsTab)
        self.delete_snippet_pushButton.setObjectName("delete_snippet_pushButton")
        self.gridLayout.addWidget(self.delete_snippet_pushButton, 0, 0, 1, 1)

        self.retranslateUi(SnippetsTab)

    def retranslateUi(self, SnippetsTab):
        _translate = QtCore.QCoreApplication.translate
        SnippetsTab.setWindowTitle(_translate("SnippetsTab", "Form"))
        self.change_font_pushButton.setText(_translate("SnippetsTab", "change Font"))
        self.new_snippet_pushButton.setText(_translate("SnippetsTab", "Add New Snippet"))
        self.delete_snippet_pushButton.setText(_translate("SnippetsTab", "Delete Snippet"))
from PyQt5 import Qsci
from pyqtsocius.ui_elements.views.snippets_tableview import SnippetsTableView
import pyqtsocius.ui_elements.pyqt_sorter_ressources_rc